import "dotenv/config";

export const env = {
  apiPort: Number(process.env.API_PORT || 3001),
  webOrigin: process.env.WEB_ORIGIN || "http://localhost:5173",
  databaseUrl: process.env.DATABASE_URL || "",
  aiBaseUrl: process.env.AI_BASE_URL || "https://api.openai.com/v1",
  aiApiKey: process.env.AI_API_KEY || "",
  aiModel: process.env.AI_MODEL || "gpt-4.1-mini",
  aiTemperature: Math.min(1, Math.max(0, Number(process.env.AI_TEMPERATURE || 0))),
  aiResponseFormatMode: (process.env.AI_RESPONSE_FORMAT_MODE || "json_object").toLowerCase(),
  aiPromptVersion: process.env.AI_PROMPT_VERSION || "about_quality_scoring_v1",
  aiMaxOutputTokens: Number(process.env.AI_MAX_OUTPUT_TOKENS || 0),
  aiInputCostPer1M: Number(process.env.AI_INPUT_COST_PER_1M || 0),
  aiOutputCostPer1M: Number(process.env.AI_OUTPUT_COST_PER_1M || 0),
  aboutSkillPath: process.env.ABOUT_SKILL_PATH || "skills/about-quality-scoring",
  faqSkillPath: process.env.FAQ_SKILL_PATH || "skills/faq-quality-scoring",
  snapshotEnabled: (process.env.SNAPSHOT_ENABLED || "true").toLowerCase() === "true",
  ingestRowConcurrency: Math.max(1, Number(process.env.INGEST_ROW_CONCURRENCY || 10)),
  ingestAdaptiveThrottleEnabled: (process.env.INGEST_ADAPTIVE_THROTTLE_ENABLED || "true").toLowerCase() === "true",
  ingestFailureStreakThreshold: Math.max(1, Number(process.env.INGEST_FAILURE_STREAK_THRESHOLD || 3)),
  ingestThrottleMs: Math.max(0, Number(process.env.INGEST_THROTTLE_MS || 2000)),
  ingestProgressFlushMs: Math.max(200, Number(process.env.INGEST_PROGRESS_FLUSH_MS || 1000)),
  ingestRowMaxRetries: Math.max(0, Number(process.env.INGEST_ROW_MAX_RETRIES || 2)),
  ingestRowRetryBaseMs: Math.max(100, Number(process.env.INGEST_ROW_RETRY_BASE_MS || 500)),
  ingestRowRetryMaxMs: Math.max(500, Number(process.env.INGEST_ROW_RETRY_MAX_MS || 5000)),
  ingestFinalRetryPasses: Math.max(0, Number(process.env.INGEST_FINAL_RETRY_PASSES || 1)),
  aiHttpMaxRetries: Math.max(0, Number(process.env.AI_HTTP_MAX_RETRIES || 2)),
  aiHttpRetryBaseMs: Math.max(100, Number(process.env.AI_HTTP_RETRY_BASE_MS || 500)),
  aiHttpRetryMaxMs: Math.max(500, Number(process.env.AI_HTTP_RETRY_MAX_MS || 5000)),
  aiRequestTimeoutMs: Math.max(1000, Number(process.env.AI_REQUEST_TIMEOUT_MS || 60000)),
  aiRequestTimeoutMsManual: Math.max(1000, Number(process.env.AI_REQUEST_TIMEOUT_MS_MANUAL || 180000)),
  aiRequestTimeoutMsBatch: Math.max(1000, Number(process.env.AI_REQUEST_TIMEOUT_MS_BATCH || 60000)),
  aiExecutorMaxRetries: Math.max(0, Number(process.env.AI_EXECUTOR_MAX_RETRIES || 2)),
};
